[plater]
size_x = 165
size_y = 165
size_z = 165
plater_path = "D:\\Projects\\PlaterFlow\\platerbinary\\plater_cli_win.exe"
[superslicer]
superslicer_path = "C:\\Users\\leand\\Desktop\\SuperSlicer_2.3.57.11_win64_220213\\superslicer_console.exe"
superslicer_config_printer = "C:\\Users\\leand\\AppData\\Roaming\\SuperSlicer\\printer\\K3.ini"
superslicer_config_filament = "C:\\Users\\leand\\AppData\\Roaming\\SuperSlicer\\filament\\FF Black K3 ASA.ini"
superslicer_config_print = "C:\\Users\\leand\\AppData\\Roaming\\SuperSlicer\\print\\K3 ABS FF.ini"